#!/usr/bin/env python3
import random

HEADER = "dogfight_header.bzw"

def vec2str(vec):
    return " ".join([str(x) for x in vec])

def make_meshbox(position, size, rotation=0, physics=None, texture=None):
    physline = f"phydrv {physics}" if physics else ""
    textureline = f"matref {texture}" if texture else ""
    return f"""meshbox
 position {vec2str(position)}
 size {vec2str(size)}
 rotation {rotation}
 {physline}
 {textureline}
end"""

def make_pyramid(position, size, rotation=0, physics=None, texture=None):
    physline = f"phydrv {physics}" if physics else ""
    textureline = f"matref {texture}" if texture else ""
    return f"""pyramid
 position {vec2str(position)}
 size {vec2str(size)}
 rotation {rotation}
 {physline}
 {textureline}
end"""


def make_shield(name, position, rotation, size, border):
    return f"""teleporter {name}
 position {vec2str(position)}
 rotation {rotation}
 size {vec2str(size)}
 border {border}
end
link
 name ln_{name}
 from {name}:f
 to {name}:f
end"""

with open(HEADER, "r") as head:
    print(head.read())

shields = [
    make_shield("red_bottom_north", [420, 300, 0], 180, [0.125, 150, 5.5], 0.9),
    make_shield("red_bottom_south", [420, -300, 0], 180, [0.125, 150, 5.5], 0.9),
    make_shield("red_top_north", [410, 300, 15], 180, [0.125, 100, 7], 0.9),
    make_shield("red_top_south", [410, -300, 15], 180, [0.125, 100, 7], 0.9),

    make_shield("red_base_front", [420, 0, 15], 180, [0.125, 15, 6], 0.9),
    make_shield("red_base_right", [450, 30, 15], 90, [0.125, 10, 6], 0.9),
    make_shield("red_base_left", [450, -30, 15], -90, [0.125, 10, 6], 0.9),

    make_shield("blue_bottom_north", [-420, 300, 0], 0, [0.125, 150, 5.5], 0.9),
    make_shield("blue_bottom_south", [-420, -300, 0], 0, [0.125, 150, 5.5], 0.9),
    make_shield("blue_top_north", [-410, 300, 15], 0, [0.125, 100, 7], 0.9),
    make_shield("blue_top_south", [-410, -300, 15], 0, [0.125, 100, 7], 0.9),

    make_shield("blue_base", [-420, 0, 15], 0, [0.125, 15, 6], 0.9),
    make_shield("blue_base_right", [-450, -30, 15], -90, [0.125, 10, 6], 0.9),
    make_shield("blue_base_left", [-450, 30, 15], 90, [0.125, 10, 6], 0.9),
]

print("")
print("### BEGIN AUTOGENERATED ###")

print("")
print("# Shields")
for s in shields:
    print(s)

print("\n# Central aisle")
print(make_meshbox([0, 0, 15], [400, 20, 1]))
print(make_meshbox([0, 19, 15], [400, 1, 2.4]))
print(make_meshbox([0, -19, 15], [400, 1, 2.4]))

print(make_meshbox([0, 0, 0], [400, 20, 2]))
print(make_meshbox([0, 19, 0], [400, 1, 3.4]))
print(make_meshbox([0, -19, 0], [400, 1, 3.4]))

#for xpos in range(-350, 400, 50):
#    print(make_meshbox([xpos, 0, 10], [20, 20, 1]))

print("\n# Islands")
for xpos in range(-300, 350, 50):
    if xpos == 0:
        continue
    for ypos in range(-280, 320, 40):
        if random.random() > 0.5:
            continue
        if random.random() > 0.5:
            print(make_meshbox([xpos + random.uniform(-8, 8),
                                ypos + random.uniform(-8, 8),
                                0],
                            size=[20+random.uniform(-5, 5),
                                  20+random.uniform(-5, 5),
                                  2 + random.uniform(0, 7)],
                            rotation=random.uniform(0, 360))
                )
        else:
            print(make_pyramid([xpos + random.uniform(-8, 8),
                                ypos + random.uniform(-8, 8),
                                0],
                            size=[10+random.uniform(-5, 2),
                                  10+random.uniform(-5, 2),
                                  8 + random.uniform(0, 7)],
                            rotation=random.uniform(0, 360),
                            texture="shiny")
                )

print("")
print("# Inner rails")
print(make_meshbox([0, 300, 5], [230, 20, 1]))
print(make_meshbox([0, -300, 5], [230, 20, 1]))

print("")
print("# Side rails")
print(make_meshbox([0, 450, 5], [270, 30, 1], physics="eastbound", texture="caution"))
print(make_meshbox([0, -450, 5], [270, 30, 1], physics="westbound", texture="caution"))

print("# Trampolines")
print(make_meshbox([300, 450, 5], [30, 30, 1],
                   physics="redtrampoline", texture="redtrampolinetex"))
print(make_meshbox([-300, -450, 5], [30, 30, 1],
                   physics="bluetrampoline", texture="bluetrampolinetex"))
